// leave off @2x/@3x
const images = {
  tabHome: require('../Images/tabHome.png'),
  Graph: require('../Images/Graph.png'),
  Barcode: require('../Images/Barcode.png'),
  buttonBack: require('../Images/button-back.png'),
  Title: require('../Images/Title.png'),
  personalIcon: require('../Images/featured-image.png'),
  idImg: require('../Images/ID.png'),
  idCover: require('../Images/idCover.png'),
  profileIcon: require('../Images/profileIcon.png'),
  eventLogo: require('../Images/eventList.png'),
  numberLogo: require('../Images/circle.png'),
  shopLogo: require('../Images/coffeeShoping.png'),
  hamburgerIcon: require('../Images/Hamburger-menu.png'),
  TitleCafe: require('../Images/TitleCafe.png'),
  profileIconBold: require('../Images/profileIconBold.png'),
  takePicture: require('../Images/takePicture.png'),
  emailCover: require('../Images/emailCover.png'),
  addressCover: require('../Images/addressCover.png'),
  aboveCover: require('../Images/aboveCover.png'),
  bottomCover: require('../Images/bottomCover.png'),
  studentCard: require('../Images/studentCard.png'),
  termContent: require('../Images/termContent.png'),
  privacyPolicyContent: require('../Images/privacyPolicyContent.png'),
  iconShop: require('../Images/iconShop.png'),
  pointBg: require('../Images/pointBg.png'),
  TitleEvent: require('../Images/TitleEvent.png'),
  TitleCompany: require('../Images/TitleCompany.png'),
  iconPersonalEvent: require('../Images/iconPersonalEvent.png'),
  Payroll: require('../Images/Payroll.png'),
  KomyMirror: require('../Images/KomyMirror.png'),
  PowerElite: require('../Images/PowerElite.png'),
  Hatena: require('../Images/Hatena.png'),
  Mercari: require('../Images/Mercari.png'),
  StartToday: require('../Images/StartToday.png'),
  Facebook: require('../Images/Facebook.png'),
  Amazon: require('../Images/Amazon.png'),
  Eureka: require('../Images/Eureka.png'),
  Tenga: require('../Images/Tenga.png'),
  Blayn: require('../Images/Blayn.png'),
  Google: require('../Images/Google.png'),
  Main: require('../Images/Main.png'),
  Overview: require('../Images/Overview.png'),
  listCalendarDark: require('../Images/listCalendarDark.png'),
  listCalendarLight: require('../Images/listCalendarLight.png'),
  listEventDark: require('../Images/listEventDark.png'),
  listEventLight: require('../Images/listEventLight.png')
};

export default images;
